name 'binford2k-arnold'
version '0.0.2'
description "This is the start of a self service provisioning system. It provides several ways manage Hiera data files and provides functions for classifying based on those data files. It can also call out to Cloud Provisioner if configured so."
description "It currently has these functions:

* Provide a REST-like API to manage Hiera YAML files with a certain structure
* Provides a graphical web interface to manage Hiera YAML files
* Provides a command line interface to manage (create, list) Hiera YAML files
* Provides a few Puppet functions to read these files and:
  * populate glabal variables (like facts or an ENC)
  * apply classes to a node
* Provides a pluggable backend for provisioning. Out of the box are:
  * Null provisioner: does nothing when called
  * Cloud Provisioner: calls out to Puppet's Cloud Provisioner to spin up, install, and classify new instances"
project_page 'https://github.com/binford2k/arnold'
