---
:sslcert:   /etc/arnold/certs/server.crt
:sslkey:    /etc/arnold/certs/server.key
:datadir:   /etc/arnold/data

:user:      admin
:password:  admin

:daemonize: false
:port:      9090

:classes:
  apache:      Manage the Apache webserver
  mysql:       Manage the MySQL database
  ntp::server: Install the NTP server
  ntp::client: Install the NTP client and configure the node to query the internal NTP server
